### ISSUE TITLE
Is there an IDatabase interface?

### ISSUE THREAD

**Issue by ThisNoName** [tmenier/AsyncPoco#25]
I was told it's easier to inject and unit test that way.

And speaking of interface, are you familiar with Insight.Database's automatic interface?  It's something like this:

    public interface IUserRepository { 
        [SQL("select * from user where id=@id")]
        List<User> GetUser(int id);

        [SQL("storedprocdoesstuff")]
        void DoStuff(Stuff stuff);
    } 

And that's it.  There's no code that actually implement the interface.  You can call them directly and the framework wires up everything

    IUserRepository repo = db.As<IUserRepository>();
    repo.GetUser(1);

Technically, this is not much different from writing inline.  But I always felt it worth the hassle just for the sake of having all SQL-ish code in one place.

**Comment by tmenier** [comment]
This has been contributed as a PR and accepted. I will update it on NuGet soon.

https://github.com/tmenier/AsyncPoco/pull/29

**Comment by tmenier** [comment]
released https://www.nuget.org/packages/AsyncPoco/1.2.0
