### ISSUE TITLE
Crash when calling ExecuteScalarAsync for a nullable integer when result is NULL

### ISSUE THREAD

**Issue by jameswilddev** [tmenier/AsyncPoco#26]
When calling ExecuteScalarAsync for a nullable integer, there's a few possible scenarios I can think of:

- One or more rows came back and the first contains an integer.  The integer should be returned.
- One or more rows came back and the first contains a non-integer.  (string, etc.)  I think this should probably throw an exception.
- One or more rows came back and the first contains NULL.  C# null should be returned.
- No rows came back.  C# null should be returned.

When the following is done: (this can also happen if you select data which is null, or when an aggregate contains no rows)

    await database.ExecuteScalarAsync<int?>(Sql.Builder.Select("NULL"))

This generates an exception:

A first chance exception of type 'System.InvalidCastException' occurred in mscorlib.dll

Additional information: Object cannot be cast from DBNull to other types.

**Comment by tmenier** [comment]
I suspect this change needs to be back-ported: https://github.com/CollaboratingPlatypus/PetaPoco/pull/280

I'll see if I can tackle this soon.

**Comment by tmenier** [comment]
fixed and will be released shortly with 1.2

**Comment by tmenier** [comment]
released https://www.nuget.org/packages/AsyncPoco/1.2.0
