### ISSUE TITLE
coonection pooling

### ISSUE THREAD

**Issue by cprashant1** [tmenier/AsyncPoco#28]
can you let me know how should we use connection pooling ? do we need to write some specific code ?
can have some sample on closing connection/ pooling connection ?

**Comment by tmenier** [comment]
You should NOT attempt to implement connection pooling yourself - this is done for you at the ADO.NET layer automatically, by default. See [here](http://stackoverflow.com/questions/7543176/ado-net-how-to-use-connection-pooling).
