### ISSUE TITLE
Invalid cast from 'System.Decimal' to 'System.Nullable'

### ISSUE THREAD

**Issue by lajjts** [tmenier/AsyncPoco#40]
I'm using AsyncPoco with Oracle to insert into a property of type ?long (nullable long) since the column in the database is nullable. Inserting works fine.

When I perform QueryAsync on the model I receive the following error:

System.InvalidCastException: Invalid cast from 'System.Decimal' to 'System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'.

So apparently AsyncPoco is incapable of selecting nullable numbers and store them in nullable long properties of pocos -- at least for Oracle.

PetaPoco appears to have had [this issue](https://github.com/CollaboratingPlatypus/PetaPoco/issues/25) with ints some time ago but that's been fixed.

**Comment by tmenier** [comment]
If this is still an issue, please post a full stack trace of the exception. I might (finally) have time to address it.
