### ISSUE TITLE
Issues with CTE Expressions

### ISSUE THREAD

**Issue by rufio620** [tmenier/AsyncPoco#41]
It appears Sql Server CTE expressions are not processed the same as in PetaPoco.

Running the following query results in an exception. 

Incorrect syntax near 'MyCTE'. If this is intended to be a common table expression, you need to explicitly terminate the previous statement with a semi-colon.Incorrect syntax near ','.

```sql
with MyCTE as
( 
	select '1000' as Test
),
MyOtherCTE as
( 
	select '1001' as Test
)
select * from MyCTE
union
select * From MyOtherCTE
```

Even when adding a ; colon certain CTE's still error out with 

Invalid object name 'Object'. Sql Exception.

It appears that asyncpoco is appending select null from [datatype] to the front of CTE queries.

```sql
SELECT NULL FROM [Object] with MyCTE as
( 
  select '1000' as Test
),
MyOtherCTE as
( 
  select '1001' as Test
)
select * from MyCTE
union
select * From MyOtherCTE
```

**Comment by rufio620** [comment]
After a little more digging it appears that the issue can be worked around by turning auto select off.

**Comment by lajjts** [comment]
I suppose the issue can be closed then?
